---
-- MIT License
--
-- Copyright (c) 2018 Clark Yang
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy of 
-- this software and associated documentation files (the "Software"), to deal in 
-- the Software without restriction, including without limitation the rights to 
-- use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
-- of the Software, and to permit persons to whom the Software is furnished to do so, 
-- subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all 
-- copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
-- SOFTWARE.
---

require("framework.System")

local AsyncTask = require("framework.AsyncTask")
local Resources = CS.UnityEngine.Resources
local GameObject = CS.UnityEngine.GameObject

---
-- 在Lua中使用try和catch
--@module TryAndCatchExample
local M=class("TryAndCatchExample",target)
---
-- 异步start函数
--
M.start = async(function(self)
		
		await(AsyncTask.Delay(1000)) --Delay 1000 milliseconds
		
		print("--------execute toPosition function----------")		
		local x,y,z = await(M.toPosition(1200,500,240))
		printf("toPosition result:x=%s y=%s z=%s",x,y,z)
		
		print("--------execute test function----------")	
		self:test()
	end)

---
--try/catch/finally 配置async使用
--下列函数是一个有返回值的函数
--
M.toPosition = async(function(x,y,z)
		--try 实际是一个函数，如果需要返回值则在try之前加return，否则不需要加return
		return try{
			function()	
				--这是主函数
				error("This a test,throw an exception")				
				return x/1000.0,y/1000.0,z/1000.0
			end,
			catch=function(e)
				--这是catch函数
				printf("Catch exception:%s",e)
				return 0,0,0 --发生异常，返回默认值
			end,
			finally =function()
				--这是finally函数
				print("Execute the finally block")
			end			
		}		
	end)

---
--try/catch/finally 独立使用
--下列是一个没有返回值的函数，当然也可以有函数值
--
function M:test()
	try{
		function()	
			--这是主函数	
			
			print("this is a test.")
			
			error("This a test,throw an exception")	
		end,
		catch = function(e)
			--这是catch函数
			printf("Catch exception:%s",e)
			return 0,0,0 --发生异常，返回默认值
		end,
		finally = function()
			--这是finally函数
			print("Execute the finally block")
		end			
	}
end

return M